site_name: Context Aware Approach Template
theme:
  name: readthedocs

plugins:
  - search
  - i18n:
      languages:
        - locale: sk
          name: Slovensky
          default: true
          build: true
        - locale: en
          name: English
          build: true
  - awesome-pages

nav:
  - Slovensky:
      - 7Ds Dashboard: sk/index.md
  - English:
      - 7Ds Dashboard: en/index.md




