import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🇬🇧 English – KNIFE',
      items: [{type: 'autogenerated', dirName: 'en'}],
    },
    {
      type: 'category',
      label: '🇸🇰 Slovenčina – KNIFE',
      items: [{type: 'autogenerated', dirName: 'sk'}],
    },
    {
      type: 'category',
      label: '📚 Docusaurus Tutorial',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: '🛠️ Docusaurus Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;
