import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🇬🇧 English – KNIFE',
      items: [{ type: 'autogenerated', dirName: 'en' }],
    },

    // ⬇️ Rozložená slovenská vetva
    {
      type: 'category',
      label: '🇸🇰 Slovenčina – KNIFE',
      collapsed: false,
      items: [
        // 7Ds (SK) necháme generovať samostatne
        {
          type: 'category',
          label: '7Ds (SK)',
          items: [{ type: 'autogenerated', dirName: 'sk/7Ds' }],
        },

        // KNIFES (SK) – pinned súbory + zvyšok autogen
        {
          type: 'category',
          label: 'KNIFES (SK)1',
          collapsed: false,
          items: [
            'sk/knifes/KNIFEsOverview',     // Základný prehľad
            'sk/knifes/KNIFE_Overview_List',
            'sk/knifes/KNIFE_Overview_Details',
            { type: 'autogenerated', dirName: 'sk/knifes' },
          ],
        },
      ],
    },

    // META (skrytá sekcia)
    {
      type: 'category',
      label: 'Meta',
      collapsed: true,
      items: [
        'sk/knifes/_meta/releasenotes', // tu bude Release
      ],
    },
  ],
};

export default sidebars;
// You can create as many sidebars as you want.