// sidebars.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Jeden spoločný sidebar; používame explicitné cesty s prefixom 'sk/'
  // a generated-index, aby sme sa neviazali na existenciu konkrétneho index.md
  docs: [
    { type: 'doc', id: 'KNIFE_HOME', label: '🏠 Domov' },
    {
      type: 'category',
      label: '🔪 KNIFEs',
      link: { type: 'generated-index', slug: '/sk/knifes/overview' },
      items: [{ type: 'autogenerated', dirName: 'sk/knifes' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🌱 7Ds',
      // POZOR na case: priečinok je '7Ds'
      link: { type: 'generated-index', slug: '/sk/7Ds/overview' },
      items: [{ type: 'autogenerated', dirName: 'sk/7Ds' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🧱 SDLC',
      link: { type: 'generated-index', slug: '/sk/sdlc/overview' },
      items: [{ type: 'autogenerated', dirName: 'sk/sdlc' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🔢 Q12',
      link: { type: 'generated-index', slug: '/sk/q12/overview' },
      items: [{ type: 'autogenerated', dirName: 'sk/q12' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🎓 STHDF',
      link: { type: 'generated-index', slug: '/sk/sthdf/overview' },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'sk/sthdf',
        },
      ],
    },
    {
      type: 'category',
      label: '🆘 Help',
      link: { type: 'generated-index', slug: '/sk/help/overview' },
      collapsed: true,
      items: [
        { type: 'doc', id: 'sk/help/release-notes', label: 'Release Notes' },
        {
          type: 'category',
          label: 'HOWTO',
          items: [
            'sk/help/howto/new-knife',
            'sk/help/howto/new-sthdf',
          ],
        },
        {
          type: 'category',
          label: 'OS Install',
          items: [
            'sk/help/os-install/index',
            'sk/help/os-install/macos',
            'sk/help/os-install/windows-msys2',
            'sk/help/os-install/linux',
          ],
        },
        { type: 'doc', id: 'sk/help/docusaurus', label: 'Docusaurus' },
      ],
    },
  ],
};

export default sidebars;