import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      // automaticky prejde všetky priečinky (sk, en)
      dirName: '.',
    },
  ],
};

export default sidebars;