import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [

    // ─── SLOVAK ───────────────────────────────────────────
    {
      type: 'category',
      label: '🆘 HELP (SK)',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'sk/help' }],
    },
    {
      type: 'category',
      label: '🔪 KNIFE (SK)',
      items: [{ type: 'autogenerated', dirName: 'sk/knifes' }],
    },
    {
      type: 'category',
      label: '🧭 7Ds (SK)',
      items: [{ type: 'autogenerated', dirName: 'sk/7Ds' }],
    },
    {
      type: 'category',
      label: '⚙️ SDLC (SK)',
      items: [{ type: 'autogenerated', dirName: 'sk/sdlc' }],
    },
    {
      type: 'category',
      label: '🎓 STHDF (SK)',
      items: [{ type: 'autogenerated', dirName: 'sk/sthdf' }],
    },
    {
      type: 'category',
      label: '📐 Q12 (SK)',
      items: [{ type: 'autogenerated', dirName: 'sk/q12' }],
    },
    {
      type: 'category',
      label: '📐 STHDF - Dashboard (SK)',
      items: [{ type: 'autogenerated', dirName: 'sk/class_sthdf_dashboard' }],
    },

    // ─── ENGLISH ──────────────────────────────────────────
    {
      type: 'category',
      label: '🆘 HELP (EN)',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'en/help' }],
    },
    {
      type: 'category',
      label: '🔪 KNIFE (EN)',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'en/knifes' }],
    },
  ],
};

export default sidebars;